"use client";

import { useState } from "react";

export default function Home() {
  const [query, setQuery] = useState("");
  const [results, setResults] = useState([]);
  const [loading, setLoading] = useState(false);
  const [statusMessage, setStatusMessage] = useState("");

  const handleSearch = async (e) => {
    e.preventDefault();
    if (!query.trim()) return;

    setLoading(true);
    setStatusMessage("");
    
    try {
      // Connect to your Dockerized Express API
      const res = await fetch(`http://localhost:3001/search?q=${encodeURIComponent(query)}`);
      const data = await res.json();
      
      if (res.status === 202) {
        // Cache Miss: The worker is crawling it
        setResults([]);
        setStatusMessage(data.message);
      } else {
        // Cache Hit: Data found
        setResults(data.results || []);
        if (data.results.length === 0) setStatusMessage("No results found.");
      }
    } catch (error) {
      console.error("Search failed:", error);
      setStatusMessage("Failed to connect to the search API.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-white text-gray-900 font-sans">
      <main className="max-w-3xl mx-auto px-4 py-12">
        
        {/* Search Header */}
        <div className="flex flex-col items-center mb-10">
          <h1 className="text-5xl font-bold mb-8 text-blue-600 tracking-tight">WikiSearch</h1>
          
          <form onSubmit={handleSearch} className="w-full flex shadow-md rounded-full bg-white border border-gray-200 overflow-hidden focus-within:shadow-lg transition-shadow">
            <input
              type="text"
              className="w-full px-6 py-4 outline-none text-lg"
              placeholder="Search the indexed web..."
              value={query}
              onChange={(e) => setQuery(e.target.value)}
            />
            <button 
              type="submit" 
              className="px-8 bg-blue-50 text-blue-600 font-semibold hover:bg-blue-100 transition-colors"
              disabled={loading}
            >
              {loading ? "Searching..." : "Search"}
            </button>
          </form>
        </div>

        {/* Status Messages (Crawling or Errors) */}
        {statusMessage && (
          <div className="text-center p-4 mb-6 rounded-lg bg-gray-50 border border-gray-100 text-gray-600 animate-pulse">
            {statusMessage}
          </div>
        )}

        {/* Results Container */}
        <div className="space-y-8">
          {results.map((result: any, index: number) => (
            <div key={index} className="group">
              <a href={result.url} target="_blank" rel="noopener noreferrer" className="block">
                <span className="text-sm text-gray-700 truncate block mb-1">
                  {result.url}
                </span>
                <h2 className="text-xl font-medium text-blue-800 group-hover:underline mb-2">
                  {result.title}
                </h2>
                {/* CRITICAL: dangerouslySetInnerHTML is required here to render 
                  the <b> tags generated by PostgreSQL's ts_headline function. 
                */}
                <p 
                  className="text-gray-600 text-sm leading-relaxed"
                  dangerouslySetInnerHTML={{ __html: result.snippet + '...' }} 
                />
              </a>
            </div>
          ))}
        </div>

      </main>
    </div>
  );
}